codecov:
  require_ci_to_pass: true
comment:                  # this is a top-level key
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
coverage:
  precision: 2
  range:
  - 60.0
  - 80.0
  round: down
  status:
    changes: false
    default_rules:
      flag_coverage_not_uploaded_behavior: include
    patch:
      default:
        target: 75.0
        threshold: 0.5
    project:
      default:
        target: 70.0
        threshold: 0.5
    github_checks:
        annotations: true
