codecov:
  require_ci_to_pass: true
  token: ccd7505c-737a-46c9-807c-a886857c5bf5
codecov:
  require_ci_to_pass: true
  token: ccd7505c-737a-46c9-807c-a886857c5bf5
comment:
  behavior: default
  require_changes: false
  layout: reach, diff, flags, files
  require_base: false
  require_changes: false
  require_head: true
  show_carryforward_flags: false
coverage:
  precision: 2
  range:
  - 60.0
  - 80.0
  round: down
  status:
    changes: false
    default_rules:
      flag_coverage_not_uploaded_behavior: include
    patch:
      default:
        target: 75.0
        threshold: 0.5
    project:
      default:
        target: 70.0
        threshold: 0.5
github_checks:
  annotations: true
